apiVersion: v1
kind: Namespace
metadata:
  name: elk

---

kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: elk
  labels:
    app: elasticsearch
spec:
  ports:
  - port: 9200
    targetPort: 9200
  selector:
    app: log-elastic

---

kind: Service
apiVersion: v1
metadata:
  name: logstash
  namespace: elk
  labels:
    app: logstash
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: log-logstash

---

kind: Service
apiVersion: v1
metadata:
  name: kanban
  namespace: elk
  labels:
    app: kanban
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
  - port: 5601
    targetPort: 5601
  selector:
    app: log-kanban

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: log-elastic
  namespace: elk
  labels:
    app: log-elastic
spec:
  selector:
    matchLabels:
      app: log-elastic
  replicas: 1
  template:
    metadata:
      labels:
        app: log-elastic
    spec:
      containers:
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
        name: log-elastic
        env:
        - name: discovery.type
          value: "single-node"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        ports:
        - containerPort: 9200
          name: elasticsearch

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: log-kanban
  namespace: elk
  labels:
    app: log-kanban
spec:
  selector:
    matchLabels:
      app: log-kanban
  replicas: 1
  template:
    metadata:
      labels:
        app: log-kanban
    spec:
      containers:
      - image: docker.elastic.co/kibana/kibana:7.4.2
        name: log-kanban
        env:
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch:9200"
        ports:
        - containerPort: 5601

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: log-logstash
  namespace: elk
  labels:
    app: log-logstash
spec:
  selector:
    matchLabels:
      app: log-logstash
  replicas: 1
  template:
    metadata:
      labels:
        app: log-logstash
    spec:
      containers:
      - image: mhus/log-logstash:7.4.2
        name: log-logstash
        ports:
        - containerPort: 5000
