apiVersion: v1
kind: Namespace
metadata:
  name: karaf

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: karaf
  namespace: karaf
spec:
  selector:
    matchLabels:
      app: karaf
  replicas: 1
  template:
    metadata:
      labels:
        app: karaf
    spec:
      hostname: karaf
      containers:
      - name: osgi
        image: mhus/apache-karaf:4.2.6_04
        stdin: true
        tty: true
        volumeMounts:
        - name: shared-logs
          mountPath: /opt/karaf/data/log
#        command: ["/bin/bash"]
      - name: filebeat
        image: mhus/log-filebeat:7.4.2
        volumeMounts:
        - name: shared-logs
          mountPath: /log
          readOnly: true
        env:
        - name: LOG_FILE
          value: "/log/karaf.log"
        - name: SERVER_TYPE
          value: "karaf"
        - name: LOGSTASH_HOST
          value: logstash.elk.svc.cluster.local:5000
        - name: LOG_LEVEL
          value: "info"
      volumes:
      - name: shared-logs
        emptyDir: {}
