apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: playground
  name: playground
spec:
  containers:
  - image: mhus/playground-pod
    name: playground
    resources: {}
    command:
    - /bin/bash
    - -c
    - "while [ true ]; do sleep 1d; done"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
